---
- name: Change password for all Active Directory users
  hosts: windows_hosts
  gather_facts: no
  tasks:
    - name: Get list of all AD users
      win_shell: Get-ADUser -Filter * | ForEach-Object { $_.SamAccountName }
      register: users

    - name: Change password for each user
      # CHANGE Password123! TO BE THE DESIRED PASSWORD!
      win_shell: Set-ADAccountPassword -Identity "{{ item }}" -Reset -NewPassword (ConvertTo-SecureString -AsPlainText "Password123!" -Force)
      loop: "{{ users.stdout_lines }}"
